spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xuegao_im?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 8
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 25000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 200000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 18000
      logAbandoned: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      
      # 配置DruidStatFilter
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          config:
            multi-statement-allow: true
            none-base-statement-allow: true
          db-type: mysql
          enabled: true
          
        web-stat-filter:
          enabled: true
          exclusions:
            - "*.js"
            - "*.gif"
            - "*.jpg"
            - "*.png"
            - "*.css"
            - "*.ico"
            - "/druid/*"
      
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        enabled: true
        reset-enable: false
        login-username: admin
        login-password: 123456
  redis:
    #url: # Connection URL. Overrides host, port, and password. User is ignored. Example: redis://user:password@example.com:6379
    #host: localhost # Redis server host.
    password: oxvwdpfuqbgzydu3 # Login password of the redis server.
    #port: 6379 # Redis server port.
    database: 0 # Database index used by the connection factory.
    ssl: false # Whether to enable SSL support.
    timeout: 3000 # Connection timeout milliseconds.
    #cluster:
    #  max-redirects: # Maximum number of redirects to follow when executing commands across the cluster.
    #  nodes: # Comma-separated list of "host:port" pairs to bootstrap from.
    sentinel:
      master: ESG_CR_CORE_REDIS_C01 # Name of the Redis server.
      nodes: esg-cr-core1.cachesit.sfdc.com.cn:8001,esg-cr-core2.cachesit.sfdc.com.cn:8001,esg-cr-core3.cachesit.sfdc.com.cn:8001 # Comma-separated list of "host:port" pairs.
    lettuce:
      pool:
        max-active: 8 # Maximum number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
        max-idle: 8 # Maximum number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
        max-wait: -1ms # Maximum amount of time a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
        min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
